# Danish Democracy settings
# DANISH_DEMOCRACY_BASE_URL and DANISH_DEMOCRACY_DEFAULT_DAYS_TO_LOAD are
# defined in .env and loaded via get_variables_from_env.

from ddd_python.ddd_utils.string_utils import normalize_danish_name  # noqa: F401 — re-exported for callers that import from here

# All 18 API entity names to retrieve data from.
DANISH_DEMOCRACY_FILE_NAMES = [
    "Afstemning",
    "Afstemningstype",
    "Aktør",
    "Aktørtype",
    "Møde",
    "Mødestatus",
    "Mødetype",
    "Periode",
    "Sag",
    "Sagstrin",
    "SagstrinAktør",
    "Sagstrinsstatus",
    "Sagstrinstype",
    "Sagskategori",
    "Sagsstatus",
    "Sagstype",
    "Stemme",
    "Stemmetype",
]

# Entities extracted incrementally using an opdateringsdato date filter.
# The remaining 12 entities also support opdateringsdato but are always
# extracted in full — they are small tables and a full extract keeps
# delete detection simple (no cursor state to manage).
DANISH_DEMOCRACY_FILE_NAMES_INCREMENTAL = [
    "Aktør",
    "Møde",
    "Sagstrin",
    "Sag",
    "SagstrinAktør",
    "Stemme",
]

# Derived from DANISH_DEMOCRACY_FILE_NAMES — one Bronze model per entity.
DANISH_DEMOCRACY_MODELS_BRONZE: list[str] = [
    f"bronze_ddd_{normalize_danish_name(name)}"
    for name in DANISH_DEMOCRACY_FILE_NAMES
]

# Derived from DANISH_DEMOCRACY_MODELS_BRONZE — parallel Silver models.
DANISH_DEMOCRACY_MODELS_SILVER: list[str] = [
    m.replace("bronze_", "silver_", 1)
    for m in DANISH_DEMOCRACY_MODELS_BRONZE
]

# Primary key column name per DDD table.  Used by the dbt model generator
# to parameterize the Silver macros and _cv views.
DANISH_DEMOCRACY_TABLE_PRIMARY_KEYS: dict[str, str] = {
    "afstemning": "id",
    "afstemningstype": "id",
    "aktoer": "id",
    "aktoertype": "id",
    "moede": "id",
    "moedestatus": "id",
    "moedetype": "id",
    "periode": "id",
    "sag": "id",
    "sagskategori": "id",
    "sagsstatus": "id",
    "sagstrin": "id",
    "sagstrinaktoer": "id",
    "sagstrinsstatus": "id",
    "sagstrinstype": "id",
    "sagstype": "id",
    "stemme": "id",
    "stemmetype": "id",
}

DANISH_DEMOCRACY_MODELS_GOLD = [
    "actor",
    "actor_type",
    "case",
    "date", # The date table is NOT generated by ddd_dbt.generate_dbt_model.py!
    "meeting",
    "meeting_status",
    "meeting_type",
    "individual_votes", # NOT generated by generate_dbt_models.py — handcrafted model!
    "vote",
    "vote_type",
]

# ── Rfam settings ────────────────────────────────────────────────────────────
# RFAM_CONNECTION_STRING and RFAM_DEFAULT_DAYS_TO_LOAD are defined in .env
# and loaded via get_variables_from_env.

# All 7 Rfam MySQL table names to extract.
RFAM_TABLE_NAMES = [
    "family",
    "genome",
    "clan",
    "clan_membership",
    "author",
    "literature_reference",
    "dead_family",
]

# Tables extracted incrementally using the `updated` timestamp column.
# The remaining tables are always extracted in full — they are small
# and a full extract keeps delete detection simple.
RFAM_TABLE_NAMES_INCREMENTAL = [
    "family",
    "genome",
]

# Derived from RFAM_TABLE_NAMES — one Bronze model per table.
RFAM_MODELS_BRONZE: list[str] = [
    f"bronze_rfam_{name}"
    for name in RFAM_TABLE_NAMES
]

# Derived from RFAM_MODELS_BRONZE — parallel Silver models.
RFAM_MODELS_SILVER: list[str] = [
    m.replace("bronze_", "silver_", 1)
    for m in RFAM_MODELS_BRONZE
]

# Primary key column name per Rfam table.  Used by the dbt model generator
# to parameterize the Silver macros and _cv views.
RFAM_TABLE_PRIMARY_KEYS: dict[str, str] = {
    "family": "rfam_acc",
    "genome": "upid",
    "clan": "clan_acc",
    "clan_membership": "rfam_acc",
    "author": "author_id",
    "literature_reference": "pmid",
    "dead_family": "rfam_acc",
}

# Source date column per Rfam table.  Incremental tables have a real
# `updated` column; full-extraction tables have none (empty string tells
# the Silver macro to derive LKHS_date_inserted_src from the filename).
RFAM_TABLE_DATE_COLUMNS: dict[str, str] = {
    "family": "updated",
    "genome": "updated",
    "clan": "updated",
    "clan_membership": "",
    "author": "",
    "literature_reference": "",
    "dead_family": "",
}

# Combined mapping of Silver model name → primary key column.
# Used by the Silver Delta Lake export to build the correct LEFT JOIN for
# incremental appends (each source system may have different PK columns).
SILVER_TABLE_PRIMARY_KEYS: dict[str, str] = {
    **{f"silver_ddd_{entity}": pk for entity, pk in DANISH_DEMOCRACY_TABLE_PRIMARY_KEYS.items()},
    **{f"silver_rfam_{entity}": pk for entity, pk in RFAM_TABLE_PRIMARY_KEYS.items()},
}

# SQL queries per Rfam table.
# - Uses SELECT * to let dlt handle schema evolution automatically.
# - The {where_clause} placeholder is replaced at runtime: incremental tables
#   get a date filter, full-extract tables get no filter.
# - Tables without an `updated` column are extracted as-is; change detection
#   in the Silver layer uses lag on the hash value partitioned by PK, ordered
#   by LKHS_date_inserted (which is NOT included in the hash).
RFAM_TABLE_QUERIES: dict[str, str] = {
    "family": (
        "SELECT * FROM family{where_clause}"
    ),
    "genome": (
        "SELECT * FROM genome{where_clause}"
    ),
    "clan": (
        "SELECT * FROM clan"
    ),
    "clan_membership": (
        "SELECT * FROM clan_membership"
    ),
    "author": (
        "SELECT * FROM author"
    ),
    "literature_reference": (
        "SELECT * FROM literature_reference"
    ),
    "dead_family": (
        "SELECT * FROM dead_family"
    ),
}
