"""Dagster software-defined assets for dbt Silver and Gold transformations.

This module integrates the dbt project (Bronze→Silver→Gold) with Dagster using
the ``dagster-dbt`` integration.  Every dbt model appears as a Dagster asset,
giving full lineage visibility from the dlt **extraction** assets through the
dbt **transformation** assets in the Dagster UI.

Lineage chain
-------------
.. code-block:: text

    dlt extraction assets  (group: ingestion/DDD)
           │   keys: AssetKey(['ingestion', 'DDD', 'afstemning']), …
           │
           ▼  (via DddDbtTranslator: source deps mapped to dlt asset keys)
    dbt Bronze models      (group: ddd_bronze)
           │   e.g. bronze_afstemning → reads OneLake JSON via DuckDB
           │
           ▼
    dbt Silver models      (group: ddd_silver)
           │   e.g. silver_afstemning → CDC incremental table
           │
           ▼
    dbt Gold models        (group: ddd_gold)
               e.g. individual_votes → star-schema fact table

Jobs
----
Two dbt run jobs are exposed via ``dbt_silver_job`` and ``dbt_gold_job``
(defined in ``jobs.py``):

* ``dbt_silver_job`` — selects ``tag:silver`` (all silver + silver_cv models).
* ``dbt_gold_job``   — selects ``tag:gold`` (all gold + gold_cv models).

Both are sequenced: silver must complete before gold.  The combined schedule
``dbt_silver_gold_schedule`` runs both in the correct order daily at 07:00 UTC
(after the 06:00 dlt extraction schedule has finished).

Resource key
------------
The ``dbt`` resource must be registered in :mod:`definitions` under the key
``"dbt"``.  It is a :class:`dagster_dbt.DbtCliResource` pointing at the
``dbt/`` subdirectory with the ``profiles_dir`` set so that dbt can locate
``profiles.yml`` at runtime.

Manifest
--------
The dbt manifest (``dbt/target/manifest.json``) must exist before Dagster
starts.  It is generated by ``dbt parse`` (or ``dbt compile``).  The CI/CD
pipeline and the ``dagster dev`` startup hook in ``dagster.yaml`` should
produce this file automatically.  During local development::

    cd dbt && dbt parse
"""

import os
from pathlib import Path
from typing import Any

from dagster import AssetExecutionContext, AssetKey, AssetSpec, Config
from dagster_dbt import DagsterDbtTranslator, DbtCliResource, DbtProject, dbt_assets

# Write dbt logs to the mounted volume so they persist across container restarts.
_DBT_LOG_PATH = os.getenv("DBT_LOGS_DIRECTORY", "/data/dbt_logs")


class DbtSilverConfig(Config):
    """Per-run configuration for Silver dbt assets.

    Set ``full_refresh: true`` in the Launchpad to pass ``--full-refresh`` to
    dbt, rebuilding all Silver tables from scratch instead of incrementally.
    """
    full_refresh: bool = False

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[2]  # …/dbt_duckdb_demo/
_DBT_PROJECT_DIR = _REPO_ROOT / "dbt"

# The DbtProject object is used by dagster-dbt to locate the manifest and
# run dbt CLI commands.
dbt_project = DbtProject(project_dir=_DBT_PROJECT_DIR)


# ---------------------------------------------------------------------------
# Custom translator: wire dbt sources → dlt extraction asset keys
# ---------------------------------------------------------------------------

class DddDbtTranslator(DagsterDbtTranslator):
    """Maps dbt model layers to Dagster asset groups and connects dbt sources
    to the upstream dlt extraction assets for full end-to-end lineage.

    Group mapping (fqn[1]):
      bronze  → ddd_bronze
      silver  → ddd_silver
      gold    → ddd_gold

    Source mapping (only for ``resource_type == "source"``):
      Source names follow the pattern ``bronze_<entity>`` — the same entity
      name that the dlt extraction assets use as their asset key.  The
      translator strips the ``bronze_`` prefix so that Dagster draws a lineage
      edge from e.g. ``AssetKey(['afstemning'])`` (the dlt asset) to
      ``AssetKey(['bronze', 'bronze_afstemning'])`` (the dbt bronze model).
    """

    _LAYER_TO_GROUP: dict[str, str] = {
        "bronze": "ddd_bronze",
        "silver": "ddd_silver",
        "gold": "ddd_gold",
    }

    def get_asset_key(self, dbt_resource_props: dict[str, Any]) -> AssetKey:
        resource_type = dbt_resource_props.get("resource_type")

        if resource_type == "source":
            # Map dbt source names to their upstream dlt extraction asset keys.
            # DDD sources:  "bronze_ddd_afstemning"   → ["ingestion", "DDD",  "afstemning"]
            # Rfam sources: "bronze_rfam_family"     → ["ingestion", "RFAM", "family"]
            source_name: str = dbt_resource_props["name"]
            bare = source_name.removeprefix("bronze_")
            if bare.startswith("rfam_"):
                return AssetKey(["ingestion", "RFAM", bare.removeprefix("rfam_")])
            if bare.startswith("ddd_"):
                return AssetKey(["ingestion", "DDD", bare.removeprefix("ddd_")])
            return AssetKey(["ingestion", "DDD", bare])

        if resource_type == "seed":
            seed_name: str = dbt_resource_props["name"]
            return AssetKey(["ingestion", "seeds", seed_name])

        # For models, use the default path-based key (prefixed by layer folder)
        return super().get_asset_key(dbt_resource_props)

    def get_group_name(self, dbt_resource_props: dict[str, Any]) -> str | None:
        resource_type = dbt_resource_props.get("resource_type")
        if resource_type == "seed":
            return "ingestion_seeds"
        fqn: list[str] = dbt_resource_props.get("fqn", [])
        # fqn = ['danish_democracy_data', 'bronze'/'silver'/'gold', 'model_name']
        layer = fqn[1] if len(fqn) >= 2 else None
        return self._LAYER_TO_GROUP.get(layer or "", layer)


# Shared translator instance used by all asset sets below
_translator = DddDbtTranslator()


# ---------------------------------------------------------------------------
# dbt assets — Seeds
# ---------------------------------------------------------------------------

@dbt_assets(
    manifest=dbt_project.manifest_path,
    project=dbt_project,
    select="resource_type:seed",
    name="dbt_seeds_assets",
    dagster_dbt_translator=_translator,
)
def dbt_seeds_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    """Load all dbt seeds (static CSV reference data) into DuckDB.

    Executes ``dbt seed`` against the local DuckDB target.  Seeds are static
    CSV files (e.g. ``publicholiday_dk``, ``LKHS_source_systems``) that are
    loaded into the ``main`` schema.  Run this job whenever the CSV files
    change or on initial setup.
    """
    yield from dbt.cli(["seed", "--log-path", _DBT_LOG_PATH], context=context).stream()


# ---------------------------------------------------------------------------
# dbt assets — Bronze layer
# ---------------------------------------------------------------------------

@dbt_assets(
    manifest=dbt_project.manifest_path,
    project=dbt_project,
    select="bronze",
    name="dbt_bronze_assets",
    dagster_dbt_translator=_translator,
)
def dbt_bronze_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    """Run all dbt Bronze models (views that read raw JSON from OneLake).

    Executes ``dbt build --select bronze`` against the local DuckDB target.
    Bronze models are thin views that read the NDJSON files written by the dlt
    extraction assets via ``read_json_auto``.  They are cheap to rebuild and
    must exist before Silver can run.

    Sources are mapped to dlt extraction asset keys via ``DddDbtTranslator``,
    creating lineage edges:  dlt:afstemning → dbt:bronze/bronze_afstemning.
    """
    yield from dbt.cli(["build", "--log-path", _DBT_LOG_PATH], context=context).stream()


# ---------------------------------------------------------------------------
# dbt assets — Silver layer
# ---------------------------------------------------------------------------

@dbt_assets(
    manifest=dbt_project.manifest_path,
    project=dbt_project,
    select="silver",
    name="dbt_silver_assets",
    dagster_dbt_translator=_translator,
)
def dbt_silver_assets(context: AssetExecutionContext, dbt: DbtCliResource, config: DbtSilverConfig):
    """Run all dbt Silver models (incremental CDC tables + current-version views).

    Executes ``dbt build --select silver`` against the local DuckDB target,
    reading from the Bronze views and writing to incremental Silver tables.

    Set ``full_refresh: true`` in the Launchpad to rebuild all Silver tables
    from scratch (passes ``--full-refresh`` to dbt).
    """
    args = ["build", "--full-refresh"] if config.full_refresh else ["build"]
    yield from dbt.cli(args + ["--log-path", _DBT_LOG_PATH], context=context).stream()


# ---------------------------------------------------------------------------
# dbt assets — Gold layer
# ---------------------------------------------------------------------------

@dbt_assets(
    manifest=dbt_project.manifest_path,
    project=dbt_project,
    select="gold",
    name="dbt_gold_assets",
    dagster_dbt_translator=_translator,
)
def dbt_gold_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    """Run all dbt Gold models (dimensional views + fact table).

    Executes ``dbt build --select gold`` against the local DuckDB target,
    reading from the Silver layer and writing to Gold views.

    Gold models are views so they rebuild cheaply on every run.  The
    ``dbt build`` command also executes the Gold data quality tests (surrogate
    key uniqueness / not-null checks).

    This asset set must run **after** ``dbt_silver_assets`` — the job
    sequencing in ``jobs.py`` enforces this order.
    """
    yield from dbt.cli(["build", "--log-path", _DBT_LOG_PATH], context=context).stream()
