-- AUTO-GENERATED by ddd_python.ddd_dbt.generate_dbt_models — do not edit by hand.
-- Regenerate with: python -m ddd_python.ddd_dbt.generate_dbt_models
--
-- Verify the SCD2 unique key constraint: no duplicate (id, LKHS_date_valid_from)
-- pairs across the DDD Silver tables (test passes when it returns no rows).
--
-- The table list is a static literal (from
-- configuration_variables.DANISH_DEMOCRACY_MODELS_SILVER) so dbt can infer the
-- test's ref() dependencies at parse time; graph.nodes is only populated at run
-- time. Rfam Silver tables are excluded: their primary keys vary per table, so a
-- GROUP BY id would be incorrect for them.

{% set silver_ddd_tables = [
    'silver_ddd_afstemning',
    'silver_ddd_afstemningstype',
    'silver_ddd_aktoer',
    'silver_ddd_aktoertype',
    'silver_ddd_moede',
    'silver_ddd_moedestatus',
    'silver_ddd_moedetype',
    'silver_ddd_periode',
    'silver_ddd_sag',
    'silver_ddd_sagskategori',
    'silver_ddd_sagsstatus',
    'silver_ddd_sagstrin',
    'silver_ddd_sagstrinaktoer',
    'silver_ddd_sagstrinsstatus',
    'silver_ddd_sagstrinstype',
    'silver_ddd_sagstype',
    'silver_ddd_stemme',
    'silver_ddd_stemmetype',
] %}

{% for table in silver_ddd_tables %}
SELECT '{{ table }}' AS table_name, id, LKHS_date_valid_from, COUNT(*) AS cnt
FROM {{ ref(table) }}
GROUP BY id, LKHS_date_valid_from
HAVING COUNT(*) > 1
    {% if not loop.last %}UNION ALL{% endif %}
{% endfor %}
